import './globals.css';
import { Montserrat } from 'next/font/google';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';

const bodyFont = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <div className="container">
          <Navbar />

          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
